# Generated by Django 2.1.7 on 2019-04-12 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20190413_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='currency',
            name='coefficient',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=datetime.datetime(2019, 4, 13, 1, 1, 48, 601220)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=datetime.datetime(2019, 4, 13, 1, 1, 48, 601220)),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
