# Generated by Django 2.1.7 on 2019-04-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20190413_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='user',
        ),
        migrations.AlterField(
            model_name='operation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='operation',
            name='purpose',
            field=models.ForeignKey(null=-1, on_delete=django.db.models.deletion.CASCADE, to='operations.Purpose'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='summ',
            field=models.FloatField(),
        ),
    ]
