# Generated by Django 2.1.7 on 2019-04-13 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20190413_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=datetime.datetime(2019, 4, 13, 21, 56, 43, 732334)),
            preserve_default=datetime.datetime(2019, 4, 13, 21, 56, 43, 732334),
        ),
    ]
