# Generated by Django 2.1.7 on 2019-04-14 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_auto_20190414_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(auto_now_add=True, null=datetime.datetime(2019, 4, 14, 14, 48, 28, 149460)),
        ),
    ]
