# Generated by Django 2.1.7 on 2019-04-14 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20190414_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='totalSum',
            field=models.FloatField(default=0, null=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purpose',
            name='totalSum',
            field=models.FloatField(default=0, null=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(auto_now_add=True, null=datetime.datetime(2019, 4, 14, 17, 10, 57, 520928)),
        ),
    ]
