# Generated by Django 2.1.7 on 2019-05-15 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_auto_20190515_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='Balance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='title',
            new_name='Title',
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 14, 54, 52, 209552)),
        ),
    ]
