# Generated by Django 2.1.7 on 2019-05-15 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_auto_20190515_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='totalSum',
            new_name='TotalSum',
        ),
        migrations.AddField(
            model_name='account',
            name='IsAccount',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 14, 57, 27, 641410)),
        ),
    ]
