# Generated by Django 2.1.7 on 2019-05-22 17:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_auto_20190522_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 20, 31, 43, 450355)),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(db_column='user', null=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 20, 31, 43, 451347)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 20, 31, 43, 452339)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 20, 31, 43, 452835)),
        ),
    ]
