# Generated by Django 2.1.7 on 2019-04-07 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20190407_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=datetime.datetime(2019, 4, 7, 19, 37, 37, 287019)),
            preserve_default=datetime.datetime(2019, 4, 7, 19, 37, 37, 287019),
        ),
        migrations.AlterField(
            model_name='operation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=datetime.datetime(2019, 4, 7, 19, 37, 37, 287019)),
        ),
    ]
