# Generated by Django 2.1.7 on 2019-04-12 21:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20190407_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=datetime.datetime(2019, 4, 13, 0, 57, 0, 921213)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='operation',
            name='purpose',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='operations.Purpose'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='summ',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=datetime.datetime(2019, 4, 13, 0, 57, 0, 921213)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
