# Generated by Django 2.1.7 on 2019-04-13 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20190413_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operation', to='operations.Purpose'),
        ),
    ]
