# Generated by Django 2.1.7 on 2019-04-20 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_auto_20190414_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 19, 45, 31, 499888)),
        ),
    ]
