# Generated by Django 2.1.7 on 2019-05-15 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_auto_20190515_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='TotalSum',
            new_name='totalSum',
        ),
        migrations.RemoveField(
            model_name='account',
            name='IsAccount',
        ),
        migrations.AddField(
            model_name='account',
            name='isAccount',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 14, 59, 38, 718706)),
        ),
    ]
