# Generated by Django 2.1.7 on 2019-05-15 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_auto_20190515_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 18, 14, 22, 316863)),
        ),
        migrations.AddField(
            model_name='category',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 18, 14, 22, 316863)),
        ),
        migrations.AddField(
            model_name='operation',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 18, 14, 22, 317864)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 18, 14, 22, 317864)),
        ),
    ]
