# Generated by Django 2.1.7 on 2019-05-15 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_auto_20190515_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='id2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 18, 21, 23, 73883)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 18, 21, 23, 73883)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 18, 21, 23, 74880)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 18, 21, 23, 74880)),
        ),
    ]
