# Generated by Django 2.1.7 on 2019-05-16 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_auto_20190515_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='key',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 15, 40, 45, 500193)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 15, 40, 45, 501190)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 15, 40, 45, 503188)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operation', to='operations.Account'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 15, 40, 45, 503188)),
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
