# Generated by Django 2.1.7 on 2019-05-22 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_auto_20190522_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 20, 27, 9, 59310)),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 20, 27, 9, 60302)),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 20, 27, 9, 61294)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 20, 27, 9, 61294)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='user',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
